### PR TITLE
trkmnkaan eklendi.

### PR DESCRIPTION
**Pull request by trkmnkaan**
trkmnkaan branch ve commit'i eklendi.

### CODE REVIEW

**Comment by trkmnkaan** [comment]
GIT error: warning: could not find UI helper 'GitHub.UI'. I tried a lot to solve this error and it is not available on every site. I guess it's a version issue. I solved my problem via cmd, not git bash. In some sources, they solved it by downloading old versions or downloading git desktop.

**Comment by electricalgorithm** [comment]
Good work, Kaan! You've accomplished the mission.

However, I have advice for you to be better at understanding standards: you should use conventional commits that we have discussed with all in the course. Now, I'll add some reviewers for your contribution, and after they'll check your PR, they will merge it.

When the mergeing process finishes, I'm going to give you permission to merge the new people's PRs.

**Comment by electricalgorithm** [comment]
@karaguven or @ardabzlk Could you squash and merge this PR -- with following conventional commit guideline?

**Comment by electricalgorithm** [comment]
@karaguven I see that you haven't followed conventional commit rules. No problem for now, but have caution about it.

**Pull request merged**
