### PR TITLE
Samet Karagüven eklendi

### PR DESCRIPTION
**Pull request by karaguven**

### CODE REVIEW

**Comment by electricalgorithm** [comment]
I see that you've not added your name on a new line but after your friend's name. Could you fix it before accepting your PR?

**Comment by karaguven** [comment]
I've fixed the problem and sent another PR.

**Comment by electricalgorithm** [comment]
Good work, Samet! You've accomplished the mission. 

@mertalitt Can you review the changes and if everything seems OK, merge it with squash and merge method? Please be carefull on conventional commit issues when creating a commit for merge operation.

**Comment by mertalitt** [comment]
Everything seems fine. Good work!

**Pull request merged**
