### PR TITLE
refactor(anladim.txt): :sparkles:

### PR DESCRIPTION
**Pull request by ardabzlk**

### CODE REVIEW

**Comment by electricalgorithm** [comment]
Can you solve the issues?

**Comment by electricalgorithm** [comment]
Thanks, Arda. You've complished the mission. I'll merge the changes you've made after some of other course-tookers saw this submission. :)

**Comment by ardabzlk** [comment]
Issue has been solved by refactoring the txt file.

**Comment by electricalgorithm** [comment]
I've added you as a collaborator -- which will let you to review and merge other people's PRs. 💯

**Pull request merged**
